export const APP_NAME = 'Restaurant Booking API';
export const DEFAULT_PAGE = 1;
export const DEFAULT_PAGE_SIZE = 20;
export const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const RATE_LIMIT_MAX_REQUESTS = 100;
export const LOGIN_RATE_LIMIT_MAX_ATTEMPTS = 5;
export const LOGIN_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const PASSWORD_RESET_TOKEN_TTL = 60 * 60; // 1 hour in seconds
export const REFRESH_TOKEN_PREFIX = 'session';
export const PASSWORD_RESET_PREFIX = 'password-reset';
